apiVersion: v1
kind: Service
metadata:
  name: temperature-app-service
spec:
  type: NodePort
  selector:
    app: temperature-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007